### ISSUE TITLE
Works great, but could you please add ability to use country abbreviations?

### ISSUE THREAD

**Issue by danim25** [dshkol/airportr#1]
It is great, but there is one additional functionality that would be cool.

This would be changing it so that if you type, for example, city_airports("London","UK"), it comes up with airports in the UK only.

Thanks for reading.

**Comment by danim25** [comment]
Just saw there is the countrycode package which can be used in conjunction.

**Comment by dshkol** [comment]
It's a useful suggestion probably worth adding. Thanks for bringing it up.
